name: offline_chat
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # State Management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  bloc_concurrency: ^0.2.5

  # Service Locator
  get_it: ^8.0.0

  # Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Storage
  flutter_secure_storage: ^9.2.2

  # HTTP
  dio: ^5.7.0

  # Routing
  go_router: ^14.6.1

  # File handling
  file_selector: ^1.0.3

  # UI
  flutter_markdown: ^0.7.4+1

  # Utils
  path: ^1.9.0
  path_provider: ^2.1.4
  intl: ^0.19.0

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Build runners
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/config/
